version: '3.3'
services:
    client:
        container_name: client
        build:
            context: client
        restart: always
        environment:
            REACT_APP_API_HOST_URI: ${REACT_APP_API_HOST_URI}
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - ./client:/client
            - /client/node_modules
        networks:
            - webappsnetwork
    api:
        container_name: api
        build:
            context: api
        restart: always
        environment:
            MONGODB_URI: ${MONGODB_URI}
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on: 
            - mongodb
        networks:
            - webappsnetwork
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            # Create a new database. Please note, the
            # /docker-entrypoint-initdb.d/mongo-init.js has to be executed
            # in order for the database to be created
            MONGO_INITDB_DATABASE: webapp
        volumes:
            # Add the mongo-init.js file to the Mongo DB container
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongodata:/data/db
        ports:
            - "27017:27017"
        networks:
            - webappsnetwork
networks:
    webappsnetwork:
        driver: bridge
volumes:
    mongodata:
