version: '3.3'
services:
    client:
        image: mhart/alpine-node:latest
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client/src/app
        volumes: 
            - ./client:/client/src/app
        entrypoint: ['npm', 'start']
        links:
            - api
        networks:
            - webappsnetwork
    api:
        build:
            dockerfile: Dockerfile
            context: api
        restart: always
        ports:
            - '9000:9000'
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on: 
            - mongodb
        networks:
            - webappsnetwork
    mongodb:
        image: mongo:4.0
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappsnetwork
networks: 
    webappsnetwork:
        driver: bridge
